### PR TITLE
Fixed Readme

### PR DESCRIPTION
**Pull request by Vehemos**
Hope this helps ^_^
Please point out errors if any.

### CODE REVIEW

**Comment by Souravirus** [comment]
@Vehemos Please include One of the contents. Remove the last contents section and add the Overview to the top.

**Comment by Vehemos** [comment]
uh I did remove it where did it come from O.0
I will do it again 1 sec

**Comment by Vehemos** [comment]
done!

**Comment by Souravirus** [comment]
@Vehemos Its looking great now.

**Pull request merged**
