### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by Skyth3r**
- Updated README with new links

### CODE REVIEW

**Comment by Souravirus** [comment]
@Skyth3r There conflicts coming in the readme.md please correct it

**Comment by Skyth3r** [comment]
Hey @Souravirus I've removed the conflict but I can't seen to be able to press the 'Resolve conflicts' button. There's a pop up that says ' These conflicts are too complex to resolve in the web editor. I'm not sure what to do now

**Comment by Souravirus** [comment]
@Skyth3r try removing the conflicts in the git bash. You will also learn how to resolve conflicts in command line

**Comment by Skyth3r** [comment]
Alright, I'll give this a go today

**Comment by Souravirus** [comment]
@Skyth3r thanks for your dedication

**Comment by Skyth3r** [comment]
Fixed everything, please check over it though as I messed around with a lot of stuff in Git

**Comment by Souravirus** [comment]
@Skyth3r Before you had sent this PR. Actually many more changes have happened. So I would have to close this PR. Sorry!

**Pull request closed without merging**
