### PR TITLE
Improved Readme + more programs + Improved File order

### PR DESCRIPTION
**Pull request by Vehemos**
Improved readme + 3 more programs from my prev contribution to a diff repo.

### CODE REVIEW

**Comment by Souravirus** [comment]
@Vehemos the readme was currently updated which is creating conflicts with your PR. So please correct it and then submit the PR. Also please check the correctness of the programs you have given. :)

**Comment by Vehemos** [comment]
Resolved

**Comment by Souravirus** [comment]
Okk great work @Vehemos

**Comment by Vehemos** [comment]
UPDATE: Improved file order

**Pull request merged**
