### PR TITLE
Removed unnecessary files, modified gitignore

### PR DESCRIPTION
**Pull request by aman935**
Modified gitignore to remove backup files (~ extension). Corrected some minor errors in name of a program. Also removed that web page from the git repo. I thought this repo is about programs, so no point in keeping a web page on it, only adds jargon to the repo. I suggest you to add :
`*.html` also if you want to keep web pages in the repo. But, the folder and other files would still remain. 

I hope you merge it asap.

### CODE REVIEW

**Comment by Souravirus** [comment]
@aman935 , Please add the .html extension in .gitignore

**Comment by aman935** [comment]
ok

**Comment by Souravirus** [comment]
Yeah its a good suggestion. I would do it

**Comment by aman935** [comment]
@Souravirus Can you merge now?

**Comment by Souravirus** [comment]
Great work @aman935

**Pull request merged**
